#!/bin/bash

~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.9999_YukawaPlaneL100_scale_0.0001.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99987_YukawaPlaneL100_scale_0.00012589.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99984_YukawaPlaneL100_scale_0.00015849.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.9998_YukawaPlaneL100_scale_0.00019953.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99975_YukawaPlaneL100_scale_0.00025119.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99968_YukawaPlaneL100_scale_0.00031623.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.9996_YukawaPlaneL100_scale_0.00039811.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.9995_YukawaPlaneL100_scale_0.00050119.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99937_YukawaPlaneL100_scale_0.00063096.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99921_YukawaPlaneL100_scale_0.00079433.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.999_YukawaPlaneL100_scale_0.001.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99874_YukawaPlaneL100_scale_0.0012589.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99842_YukawaPlaneL100_scale_0.0015849.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.998_YukawaPlaneL100_scale_0.0019953.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99749_YukawaPlaneL100_scale_0.0025119.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99684_YukawaPlaneL100_scale_0.0031623.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99602_YukawaPlaneL100_scale_0.0039811.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99499_YukawaPlaneL100_scale_0.0050119.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99369_YukawaPlaneL100_scale_0.0063096.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99206_YukawaPlaneL100_scale_0.0079433.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.99_YukawaPlaneL100_scale_0.01.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.98741_YukawaPlaneL100_scale_0.012589.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.98415_YukawaPlaneL100_scale_0.015849.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.98005_YukawaPlaneL100_scale_0.019953.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.97488_YukawaPlaneL100_scale_0.025119.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.96838_YukawaPlaneL100_scale_0.031623.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.96019_YukawaPlaneL100_scale_0.039811.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.94988_YukawaPlaneL100_scale_0.050119.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.9369_YukawaPlaneL100_scale_0.063096.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.92057_YukawaPlaneL100_scale_0.079433.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.9_YukawaPlaneL100_scale_0.1.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.87411_YukawaPlaneL100_scale_0.12589.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.84151_YukawaPlaneL100_scale_0.15849.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.80047_YukawaPlaneL100_scale_0.19953.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.74881_YukawaPlaneL100_scale_0.25119.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.68377_YukawaPlaneL100_scale_0.31623.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.60189_YukawaPlaneL100_scale_0.39811.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.49881_YukawaPlaneL100_scale_0.50119.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.36904_YukawaPlaneL100_scale_0.63096.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0.20567_YukawaPlaneL100_scale_0.79433.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0 --perturbation-file pseudopotentials_V1_scale_0_YukawaPlaneL100_scale_1.dat --perturbation-strength 1 -g --use-lapack --eigenstate -n 1;

# delete all vec files other than ky=3
mkdir safe
mv *.dat safe
mv *ky_3* safe
rm *.vec
mv safe/* .
rm -r safe
