#!/bin/bash

runs() {
for i in {2..98..2}
do
#	KY=$(cat ../vectors/ypt/l0p0001/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.0001_trunc_"$i"_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#	echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l0p0001/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.0001_trunc_"$i"_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL0.0001.dat --perturbation-strength 1 --nbr-perturbation $i --sr-qy-momentum 0
#	KY=$(cat ../vectors/ypt/l0p001/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.001_trunc_"$i"_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#	echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l0p001/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.001_trunc_"$i"_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL0.001.dat --perturbation-strength 1 --nbr-perturbation $i --sr-qy-momentum 0
#	KY=$(cat ../vectors/ypt/l0p01/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.01_trunc_"$i"_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#	echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l0p01/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.01_trunc_"$i"_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL0.01.dat --perturbation-strength 1 --nbr-perturbation $i --sr-qy-momentum 0
#	KY=$(cat ../vectors/ypt/l0p1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.1_trunc_"$i"_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#	echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l0p1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.1_trunc_"$i"_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL0.1.dat --perturbation-strength 1 --nbr-perturbation $i --sr-qy-momentum 0
#	KY=$(cat ../vectors/ypt/l1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_trunc_"$i"_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#	echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_trunc_"$i"_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL1.dat --perturbation-strength 1 --nbr-perturbation $i --sr-qy-momentum 0
	KY=$(cat ../vectors/ypt/l100/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL100_trunc_"$i"_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
	echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l100/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL100_trunc_"$i"_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL100.dat --perturbation-strength 1 --nbr-perturbation $i --sr-qy-momentum 0
done

#KY=$(cat ../vectors/ypt/l0p0001/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.0001_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l0p0001/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.0001_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL0.0001.dat --perturbation-strength 1 --nbr-perturbation 100 --sr-qy-momentum 0
#
#KY=$(cat ../vectors/ypt/l0p001/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.001_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l0p001/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.001_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL0.001.dat --perturbation-strength 1 --nbr-perturbation 100 --sr-qy-momentum 0
#
#KY=$(cat ../vectors/ypt/l0p01/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.01_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l0p01/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.01_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL0.01.dat --perturbation-strength 1 --nbr-perturbation 100 --sr-qy-momentum 0
#
#KY=$(cat ../vectors/ypt/l0p1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.1_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l0p1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL0.1_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL0.1.dat --perturbation-strength 1 --nbr-perturbation 100 --sr-qy-momentum 0
#
#KY=$(cat ../vectors/ypt/l1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
#echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL1.dat --perturbation-strength 1 --nbr-perturbation 100 --sr-qy-momentum 0

KY=$(cat ../vectors/ypt/l100/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL100_n_6_2s_18_ratio_1.000000.dat | sort -k2,2g | awk 'NR == 2 { print $1 }')
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse ../vectors/ypt/l100/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL100_n_6_2s_18_ratio_1.000000_ky_"$KY".0.vec --sr-omega-min -100 --sr-omega-max 100 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file ../vectors/ypt/pseudopotentials_YukawaPlaneL100.dat --perturbation-strength 1 --nbr-perturbation 100 --sr-qy-momentum 0
}
export -f runs
runs | nohup parallel -j 4 > nohup.out &
