#!/bin/bash

runs() {
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /home/bart/PycharmProjects/response_functions/vectors_2/ypt/n_8_lambda_1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_trunc_2_n_8_2s_24_ratio_1.000000_ky_20.0.vec --sr-omega-min -20 --sr-omega-max 0 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file /home/bart/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_YukawaPlaneL1.dat --perturbation-strength 1 --nbr-perturbation 2 -y 0 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /home/bart/PycharmProjects/response_functions/vectors_2/ypt/n_8_lambda_1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_trunc_4_n_8_2s_24_ratio_1.000000_ky_20.0.vec --sr-omega-min -20 --sr-omega-max 0 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file /home/bart/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_YukawaPlaneL1.dat --perturbation-strength 1 --nbr-perturbation 4 -y 0 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /home/bart/PycharmProjects/response_functions/vectors_2/ypt/n_8_lambda_1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_trunc_6_n_8_2s_24_ratio_1.000000_ky_20.0.vec --sr-omega-min -20 --sr-omega-max 0 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file /home/bart/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_YukawaPlaneL1.dat --perturbation-strength 1 --nbr-perturbation 6 -y 0 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /home/bart/PycharmProjects/response_functions/vectors_2/ypt/n_8_lambda_1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_trunc_8_n_8_2s_24_ratio_1.000000_ky_12.0.vec --sr-omega-min -20 --sr-omega-max 0 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file /home/bart/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_YukawaPlaneL1.dat --perturbation-strength 1 --nbr-perturbation 8 -y 0 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /home/bart/PycharmProjects/response_functions/vectors_2/ypt/n_8_lambda_1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_trunc_10_n_8_2s_24_ratio_1.000000_ky_20.0.vec --sr-omega-min -20 --sr-omega-max 0 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file /home/bart/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_YukawaPlaneL1.dat --perturbation-strength 1 --nbr-perturbation 10 -y 0 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /home/bart/PycharmProjects/response_functions/vectors_2/ypt/n_8_lambda_1/fermions_torus_kysym_coulomb_0_plus_YukawaPlaneL1_trunc_12_n_8_2s_24_ratio_1.000000_ky_20.0.vec --sr-omega-min -20 --sr-omega-max 0 --sr-epsilon 1E-4 --sr-omega-interval 1E-5 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 0 --perturbation-file /home/bart/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_YukawaPlaneL1.dat --perturbation-strength 1 --nbr-perturbation 12 -y 0 -m 8000
}
export -f runs
runs | nohup nice parallel -j 4 &
