#!/bin/bash

runs() {
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0001 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.9999 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.025097 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.9749 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.050095 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.9499 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.075092 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.92491 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.10009 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.89991 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.12509 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.87491 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.15008 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.84991 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.17508 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.82492 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.20008 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.79992 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.22508 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.77492 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.25007 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.74992 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.27507 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.72493 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.30007 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.69993 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.32507 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.67493 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.35006 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.64994 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.37506 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.62494 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.40006 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.59994 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.42506 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.57494 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.45005 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.54995 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.47505 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.52495 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.50005 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.49995 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.52505 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.47495 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.55005 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.44995 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.57504 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.42496 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.60004 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.39996 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.62504 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.37496 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.65003 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.34997 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.67503 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.32497 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.70003 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.29997 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.72503 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.27497 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.75002 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.24998 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.77502 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.22498 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.80002 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.19998 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.82502 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.17498 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.85001 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.14999 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.87501 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.12499 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.90001 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.09999 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.92501 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.074993 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.95 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.049995 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.975 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0.024998 -g --use-lapack --eigenstate -n 1 -m 8000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 1 --perturbation-file ~/PycharmProjects/response_functions/pseudopotentials/plane/pseudopotentials_V1.dat --perturbation-strength 0 -g --use-lapack --eigenstate -n 1 -m 8000
}
export -f runs
runs | nohup nice parallel -j 4 &
