#!/bin/bash

runs() {
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/n_8/fermions_torus_kysym_yukawa-0.0001_plus_V1_scale_0_n_8_2s_24_ratio_1.000000_ky_4.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 0.00001 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.0001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0 -S --processors 8 -m 100000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/n_8/fermions_torus_kysym_yukawa-0.001_plus_V1_scale_0_n_8_2s_24_ratio_1.000000_ky_4.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 0.00001 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0 -S --processors 8 -m 100000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/n_8/fermions_torus_kysym_yukawa-0.01_plus_V1_scale_0_n_8_2s_24_ratio_1.000000_ky_4.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 0.00001 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.01 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0 -S --processors 8 -m 100000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/n_8/fermions_torus_kysym_yukawa-0.1_plus_V1_scale_0_n_8_2s_24_ratio_1.000000_ky_4.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 0.00001 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0 -S --processors 8 -m 100000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/n_8/fermions_torus_kysym_yukawa-1_plus_V1_scale_0_n_8_2s_24_ratio_1.000000_ky_4.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 0.00001 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0 -S --processors 8 -m 100000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/n_8/fermions_torus_kysym_yukawa-10_plus_V1_scale_0_n_8_2s_24_ratio_1.000000_ky_4.0.vec --sr-omega-min -10 --sr-omega-max -9.5 --sr-epsilon 0.0001 --sr-omega-interval 0.00001 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 10 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0 -S --processors 8 -m 100000
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/n_8/fermions_torus_kysym_yukawa-100_plus_V1_scale_0_n_8_2s_24_ratio_1.000000_ky_4.0.vec --sr-omega-min -10 --sr-omega-max -9.95 --sr-epsilon 0.0001 --sr-omega-interval 0.00001 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 100 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0 -S --processors 8 -m 100000
}
export -f runs
runs | nohup nice parallel -j 4 > nohup.out &
