#!/bin/bash

runs() {
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.0001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 1e-05 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.0001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.0001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.75 --sr-omega-max -6.25 --sr-epsilon 5e-05 --sr-omega-interval 5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.0001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.0001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.125 --sr-omega-max -6.875 --sr-epsilon 2.5e-05 --sr-omega-interval 2.5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.0001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.0001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.8125 --sr-omega-max -7.1875 --sr-epsilon 1.25e-05 --sr-omega-interval 1.25e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.0001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.0001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.65625 --sr-omega-max -7.34375 --sr-epsilon 6.25e-06 --sr-omega-interval 6.25e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.0001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.0001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.57812 --sr-omega-max -7.42188 --sr-epsilon 3.125e-06 --sr-omega-interval 3.125e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.0001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.0001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.53906 --sr-omega-max -7.46094 --sr-epsilon 1.5625e-06 --sr-omega-interval 1.5625e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.0001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 1e-05 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.75 --sr-omega-max -6.25 --sr-epsilon 5e-05 --sr-omega-interval 5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.125 --sr-omega-max -6.875 --sr-epsilon 2.5e-05 --sr-omega-interval 2.5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.8125 --sr-omega-max -7.1875 --sr-epsilon 1.25e-05 --sr-omega-interval 1.25e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.65625 --sr-omega-max -7.34375 --sr-epsilon 6.25e-06 --sr-omega-interval 6.25e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.57812 --sr-omega-max -7.42188 --sr-epsilon 3.125e-06 --sr-omega-interval 3.125e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.001_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.53906 --sr-omega-max -7.46094 --sr-epsilon 1.5625e-06 --sr-omega-interval 1.5625e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.001 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.01_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 1e-05 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.01 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.01_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.75 --sr-omega-max -6.25 --sr-epsilon 5e-05 --sr-omega-interval 5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.01 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.01_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.125 --sr-omega-max -6.875 --sr-epsilon 2.5e-05 --sr-omega-interval 2.5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.01 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.01_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.8125 --sr-omega-max -7.1875 --sr-epsilon 1.25e-05 --sr-omega-interval 1.25e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.01 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.01_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.65625 --sr-omega-max -7.34375 --sr-epsilon 6.25e-06 --sr-omega-interval 6.25e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.01 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.01_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.57812 --sr-omega-max -7.42188 --sr-epsilon 3.125e-06 --sr-omega-interval 3.125e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.01 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.01_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.53906 --sr-omega-max -7.46094 --sr-epsilon 1.5625e-06 --sr-omega-interval 1.5625e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.01 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 1e-05 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.75 --sr-omega-max -6.25 --sr-epsilon 5e-05 --sr-omega-interval 5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.125 --sr-omega-max -6.875 --sr-epsilon 2.5e-05 --sr-omega-interval 2.5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.8125 --sr-omega-max -7.1875 --sr-epsilon 1.25e-05 --sr-omega-interval 1.25e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.65625 --sr-omega-max -7.34375 --sr-epsilon 6.25e-06 --sr-omega-interval 6.25e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.57812 --sr-omega-max -7.42188 --sr-epsilon 3.125e-06 --sr-omega-interval 3.125e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-0.1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.53906 --sr-omega-max -7.46094 --sr-epsilon 1.5625e-06 --sr-omega-interval 1.5625e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 0.1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -10 --sr-omega-max -5 --sr-epsilon 0.0001 --sr-omega-interval 1e-05 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.75 --sr-omega-max -6.25 --sr-epsilon 5e-05 --sr-omega-interval 5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -8.125 --sr-omega-max -6.875 --sr-epsilon 2.5e-05 --sr-omega-interval 2.5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.8125 --sr-omega-max -7.1875 --sr-epsilon 1.25e-05 --sr-omega-interval 1.25e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.65625 --sr-omega-max -7.34375 --sr-epsilon 6.25e-06 --sr-omega-interval 6.25e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.57812 --sr-omega-max -7.42188 --sr-epsilon 3.125e-06 --sr-omega-interval 3.125e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-1_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -7.53906 --sr-omega-max -7.46094 --sr-epsilon 1.5625e-06 --sr-omega-interval 1.5625e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 1 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-10_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -10 --sr-omega-max -9.5 --sr-epsilon 0.0001 --sr-omega-interval 1e-05 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 10 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-10_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.875 --sr-omega-max -9.625 --sr-epsilon 5e-05 --sr-omega-interval 5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 10 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-10_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.8125 --sr-omega-max -9.6875 --sr-epsilon 2.5e-05 --sr-omega-interval 2.5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 10 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-10_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.78125 --sr-omega-max -9.71875 --sr-epsilon 1.25e-05 --sr-omega-interval 1.25e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 10 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-10_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.76562 --sr-omega-max -9.73438 --sr-epsilon 6.25e-06 --sr-omega-interval 6.25e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 10 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-10_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.75781 --sr-omega-max -9.74219 --sr-epsilon 3.125e-06 --sr-omega-interval 3.125e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 10 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-10_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.75391 --sr-omega-max -9.74609 --sr-epsilon 1.5625e-06 --sr-omega-interval 1.5625e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 10 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-100_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -10 --sr-omega-max -9.95 --sr-epsilon 0.0001 --sr-omega-interval 1e-05 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 100 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-100_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.9875 --sr-omega-max -9.9625 --sr-epsilon 5e-05 --sr-omega-interval 5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 100 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-100_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.98125 --sr-omega-max -9.96875 --sr-epsilon 2.5e-05 --sr-omega-interval 2.5e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 100 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-100_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.97813 --sr-omega-max -9.97187 --sr-epsilon 1.25e-05 --sr-omega-interval 1.25e-06 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 100 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-100_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.97656 --sr-omega-max -9.97344 --sr-epsilon 6.25e-06 --sr-omega-interval 6.25e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 100 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-100_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.97578 --sr-omega-max -9.97422 --sr-epsilon 3.125e-06 --sr-omega-interval 3.125e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 100 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusSpectralResponse /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/fermions_torus_kysym_yukawa-100_plus_V1_scale_0_n_6_2s_18_ratio_1.000000_ky_3.0.vec --sr-omega-min -9.97539 --sr-omega-max -9.97461 --sr-epsilon 1.5625e-06 --sr-omega-interval 1.5625e-07 --sr-spectral-resolution 1E-5 --use-coulomb --coulomb-strength 1 --yukawa-mass 100 --perturbation-file /disk/data11/tfp/BartMadhav/project3/vectors/yukawa/pseudopotentials_V1.dat --perturbation-strength 0 --sr-qy-momentum 0
}
export -f runs
runs | nohup nice parallel -j 4 > nohup.out &
