#!/bin/bash

runs() {
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0001 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.9999 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.00012589 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99987 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.00015849 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99984 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.00019953 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.9998 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.00025119 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99975 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.00031623 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99968 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.00039811 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.9996 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.00050119 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.9995 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.00063096 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99937 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.00079433 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99921 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.001 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.999 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0012589 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99874 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0015849 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99842 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0019953 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.998 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0025119 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99749 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0031623 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99684 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0039811 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99602 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0050119 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99499 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0063096 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99369 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.0079433 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99206 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.01 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.99 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.012589 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.98741 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.015849 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.98415 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.019953 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.98005 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.025119 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.97488 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.031623 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.96838 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.039811 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.96019 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.050119 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.94988 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.063096 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.9369 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.079433 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.92057 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.1 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.9 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.12589 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.87411 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.15849 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.84151 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.19953 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.80047 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.25119 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.74881 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.31623 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.68377 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.39811 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.60189 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.50119 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.49881 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.63096 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.36904 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 0.79433 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0.20567 -g --use-lapack --eigenstate -n 1;
echo ~/DiagHam_latest/build/FQHE/src/Programs/FQHEOnTorus/FQHETorusFermionsCoulomb -p 6 -l 18 --landau-level 0 --coulomb-strength 1 --yukawa-mass 0.0001 --perturbation-file pseudopotentials_V1.dat --perturbation-strength 0 -g --use-lapack --eigenstate -n 1;
}
export -f runs
runs | nohup parallel -j 6 > nohup.out;

# delete all vec files other than ky=3
mkdir safe
mv *.dat safe
mv *ky_3* safe
rm *.vec
mv safe/* .
rm -r safe
